version: '3'

services:
  db:
    hostname: 'db'
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'my-app-db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'

    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  
  redis:
    container_name: 'redis'
    image: 'redis:3.2.0'


  django:
    build: 
      context: . 
      dockerfile: ./Dockerfile
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "mailing.wsgi:application"]
    environment:
      WAIT_HOSTS: db:3306
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
  rq:
    build: .
    command: python manage.py rqworker
    links:
      - redis